name: RadiRoot
version: "2.10"
license: "GPL-2.0-or-later"
date: 2026-08-11
description: |
    Roots of a Polynomial as Radicals

authors:
    - name: Andreas Distler
      url: mailto:a.distler@tu-bs.de

maintainers:
    - name: The GAP Team
      url: mailto:support@gap-system.org

GAP: ">=4.9"

needed-pkgs:
    - name: "Alnuth"
      version: ">=3.0"
      url: "https://gap-packages.github.io/alnuth"
    - name: "TransGrp"
      version: ">=1.0"
      url: "https://www.math.colostate.edu/~hulpke/transgrp"

www: https://gap-packages.github.io/radiroot/
readme: README.md
packageinfo: https://gap-packages.github.io/radiroot/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/radiroot/releases/download/v2.10/radiroot-2.10.tar.gz

abstract: |
    The <span class="pkgname">RadiRoot</span> package installs a method to    display the roots of a rational polynomial as radicals if it is solvable.

status: accepted
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    roots, radicals.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Dis26</span>]   <b class='BibAuthor'>Distler, A.</b>,
     <i class='BibTitle'>RadiRoot, Roots of a Polynomial as Radicals,
             Version 2.10</i>
     (<span class='BibYear'>2026</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/radiroot/">https://gap-packages.github.io/radiroot/</a></span>.
    </p>
    

bibtex: |
    @misc{ RadiRoot,
      author =           {Distler, A.},
      title =            {{RadiRoot},  {Roots  of  a  Polynomial  as  Radicals},
                          {V}ersion 2.10},
      month =            {Aug},
      year =             {2026},
      note =             {GAP package},
      howpublished =     {\href       {https://gap-packages.github.io/radiroot/}
                          {\texttt{https://gap\texttt{\symbol{45}}packages.github.io/}\discretionary
                          {}{}{}\texttt{radiroot/}}},
      keywords =         {roots; radicals},
      printedkey =       {Dis26}
    }

