# RadiRoot, chapter 2
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("radiroot01.tst");

# doc/radiroot.xml:39-69
gap> x := Indeterminate( Rationals, "x" );;
gap> f := UnivariatePolynomial( Rationals, [1,3,4,1] );
x^3+4*x^2+3*x+1
gap> L := SplittingField( f );
<algebraic extension over the Rationals of degree 6>
gap> y := Indeterminate( L, "y" );;
gap> FactorsPolynomialAlgExt( L, f );
[ y+(-3/94*a^4-24/47*a^3-253/94*a^2-535/94*a-168/47), 
  y+(-3/94*a^4-24/47*a^3-253/94*a^2-441/94*a+20/47), 
  y+(3/47*a^4+48/47*a^3+253/47*a^2+488/47*a+336/47) ]
gap> IsomorphicMatrixField( L );
<rational matrix field of degree 6>
gap> Display(RootsAsMatrices(f)[1]);
[ [   0,   1,   0,   0,   0,   0 ],
  [   0,   0,   1,   0,   0,   0 ],
  [  -1,  -3,  -4,   0,   0,   0 ],
  [   0,   0,   0,   0,   1,   0 ],
  [   0,   0,   0,   0,   0,   1 ],
  [   0,   0,   0,  -1,  -3,  -4 ] ]
gap> MinimalPolynomial( Rationals, RootsAsMatrices(f)[1]);
x^3+4*x^2+3*x+1
gap> iso := IsomorphismMatrixField( L );
MappingByFunction( <algebraic extension over the Rationals of degree 
6>, <rational matrix field of degree 
6>, function( x ) ... end, function( mat ) ... end )
gap> PreImages( iso, RootsAsMatrices( f ) );
[ -3/47*a^4-48/47*a^3-253/47*a^2-488/47*a-336/47, 
  3/94*a^4+24/47*a^3+253/94*a^2+441/94*a-20/47, 
  3/94*a^4+24/47*a^3+253/94*a^2+535/94*a+168/47 ]

# doc/radiroot.xml:80-83
gap> GaloisGroupOnRoots(f);
Group([ (2,3), (1,2) ])

# doc/radiroot.xml:201-208
gap> g := UnivariatePolynomial( Rationals, [1,1,-1,-1,1] );;
gap> RootsOfPolynomialAsRadicalsNC( g, "off" );
gap> SplittingField( g );
<algebraic extension over the Rationals of degree 8>
gap> GaloisGroupOnRoots( g );
Group([ (2,4), (1,2)(3,4) ])

#
gap> STOP_TEST("radiroot01.tst", 1);
