# RadiRoot, chapter 3
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("radiroot02.tst");

# doc/info.xml:23-29
gap> InfoLevel(InfoRadiroot);
1
gap> RootsOfPolynomialAsRadicals(x^5-4*x+2);
#I  Polynomial is not solvable.
fail

#
gap> STOP_TEST("radiroot02.tst", 1);
